// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: health.sql

package database

import (
	"context"
)

const checkDatabaseHealth = `-- name: CheckDatabaseHealth :one
SELECT
    1
`

func (q *Queries) CheckDatabaseHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkDatabaseHealth)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
