openapi: 3.0.0
info:
  title: RSSFeedAggregator
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /v1/healthz:
    get:
      tags:
        - default
      summary: Health
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/user:
    post:
      tags:
        - default
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Moises Dennis
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get User By API Key
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/feeds:
    post:
      tags:
        - default
      summary: Create Feed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: newyorker
                url: https://www.newyorker.com/feed/news
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get Feeds
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/feed_follows:
    post:
      tags:
        - default
      summary: Create Feed Follow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                feed_id: yyyyyy-yyyyy-yyyy
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get Feed Follows
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/feed_follows/{id}:
    delete:
      tags:
        - default
      summary: Delete Feed Follow
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/posts:
    get:
      tags:
        - default
      summary: Get New Posts
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            APIKey
            xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}